name: Test and Deploy

on: push

jobs:
  test:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest 
        
  deploy:
    needs: test
    runs-on: ubuntu-20.04
    
    steps:
      - name: login to server using ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }} 
          port: 22
          script: |
            cd Continuous_deployment-/
            git pull
            git status
            ls
            cat README.md
